/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2024-12-28 15:20:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(session.getAttribute("name")==null){
		response.sendRedirect("login.jsp");
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"author\" content=\"\" />\n");
      out.write("<title>LoginSignUp using jsp,servlet, mysql & Tomcat</title>\n");
      out.write("<!-- Favicon-->\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\n");
      out.write("<!-- Font Awesome icons (free version)-->\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.15.4/js/all.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- Google fonts-->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\"\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("<link href=\"css/index-styles.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("<body id=\"page-top\">\n");
      out.write("	<!-- Navigation-->\n");
      out.write("	<nav\n");
      out.write("		class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\"\n");
      out.write("		id=\"mainNav\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<a class=\"navbar-brand\" href=\"#page-top\">LoginSignUp</a>\n");
      out.write("			<button\n");
      out.write("				class=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\"\n");
      out.write("				type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("				data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("				Menu <i class=\"fas fa-bars\"></i>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\n");
      out.write("					\n");
      out.write("						<li class=\"nav-item mx-0 mx-lg-1 bg-danger\"><a\n");
      out.write("						class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"logout\">Logout>");
      out.print(session.getAttribute("name") );
      out.write("</a></li>\n");
      out.write("					\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<!-- Masthead-->\n");
      out.write("	<header class=\"masthead bg-primary text-white text-center\">\n");
      out.write("		<div class=\"container d-flex align-items-center flex-column\">\n");
      out.write("			<!-- Masthead Avatar Image-->\n");
      out.write("			\n");
      out.write("			<!-- Masthead Heading-->\n");
      out.write("			<h1 class=\"masthead-heading text-uppercase mb-0\">HomePage</h1>\n");
      out.write("			<!-- Icon Divider-->\n");
      out.write("			\n");
      out.write("	</div>\n");
      out.write("	</header>\n");
      out.write("	<!-- Bootstrap core JS-->\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<!-- Core theme JS-->\n");
      out.write("	<script src=\"js/scripts.js\"></script>\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("	<!-- * *                               SB Forms JS                               * *-->\n");
      out.write("	<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\n");
      out.write("	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n");
      out.write("	<script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
